### ISSUE TITLE
What is "pre"

### ISSUE THREAD

**Issue by Mr-Lion** [CesiumGS/strip-pragma-loader#5]
Hi,

what is pre?

![image](https://user-images.githubusercontent.com/6929357/144713302-d8ec73c3-bee4-47e1-acb8-044a73fb1ea7.png)

![image](https://user-images.githubusercontent.com/6929357/144713312-5574f42c-5688-462d-9acd-86e4d4deb7ea.png)

**Comment by charlesritchea** [comment]
@Mr-Lion webpack modules are split into 'pre', normal (default), and 'post' groups that run in that order

**Comment by jjspace** [comment]
Looks like it's just an error of the documentation. The pre should be a string not a variable, just wrap it in quotes like `enforce: 'pre',`
