### ISSUE TITLE
Vulnerability in `loader-utils` dependency

### ISSUE THREAD

**Issue by vividos** [CesiumGS/strip-pragma-loader#7]
I'm using `strip-pragma-loader` version 1.0.1 in an npm project of mine, and since yesterday I get a warning about a vulnerability in a dependency of `strip-pragma-loader`, webpack's `loader-utils`, e.g. when running `npm audit`:

```
# npm audit report

loader-utils  <2.0.3
Severity: critical
Prototype pollution in webpack loader-utils - https://github.com/advisories/GHSA-76p3-8jx3-jpfq
No fix available
node_modules/loader-utils
  strip-pragma-loader  *
  Depends on vulnerable versions of loader-utils
  node_modules/strip-pragma-loader

2 critical severity vulnerabilities
```

Can the `loader-utils` easily be updated to the latest version, or at least the non-vulnerable version 2.0.3? That would be great! Thanks!

**Comment by ggetz** [comment]
Thanks fort the report @vividos! It should be possible to bump the version to https://github.com/webpack/loader-utils/releases/tag/v1.4.1, which fixes the vulnerability I believe you're speaking of, without much churn.

**Comment by vividos** [comment]
Right, 1.4.1 also has the fix. Thanks for the quick action!
